ALTER DATABASE [$(DatabaseName)]
    ADD FILE (NAME = [Bible], FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Bible.mdf', SIZE = 97280 KB, FILEGROWTH = 1024 KB) TO FILEGROUP [PRIMARY];

