//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Core.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Switch
    {
        public int RecordID { get; set; }
        public Nullable<System.DateTime> InsertDT { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string SwitchDescription { get; set; }
        public bool SwitchStatus { get; set; }
    }
}
