ALTER TABLE [dbo].[VersesBasicEnglish]
    ADD CONSTRAINT [PK_RecID_VerseBasicEnglish] PRIMARY KEY CLUSTERED ([RecID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

