//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.ConsoleEntityTest.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskList
    {
        public int TaskId { get; set; }
        public string TaskName { get; set; }
        public string TaskText { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
